Dev
TMcreative1/playwright-client-kotlin pull request #17
Opened 2021-04-23 15:08 UTC by TMcreative1

2021-04-23 15:32 UTC, Roman-Mitusov requested changes

2021-04-23 15:32 UTC, Roman-Mitusov commented on src/main/kotlin/com/playwright/remote/engine/download/impl/Download.kt
> +    private var browser: IBrowser = (parent as IBrowserContext).browser()
This property of Download class is not used inside the class.
Remove it or make use of it.

2021-04-23 15:46 UTC, Roman-Mitusov commented
Please make sure that our remote API is compatible with current Playwright API. There was a slight changes at least in Download and Video API of Playwright.

2021-04-26 13:11 UTC, Roman-Mitusov requested changes

2021-04-26 13:14 UTC, TMcreative1 commented on src/main/kotlin/com/playwright/remote/engine/options/CheckOptions.kt
> +    private val builder: IBuilder<CheckOptions>
```suggestion
    @Transient private val builder: IBuilder<CheckOptions>
```

2021-04-26 15:22 UTC, Roman-Mitusov requested changes

2021-04-26 15:22 UTC, Roman-Mitusov commented on src/main/kotlin/com/playwright/remote/engine/options/element/ScrollIntoViewIfNeededOptions.kt
> +    private val builder: IBuilder<ScrollIntoViewIfNeededOptions>
Please add @Trancient annotation to this field

2021-04-26 15:23 UTC, TMcreative1 commented on src/main/kotlin/com/playwright/remote/engine/options/element/ScrollIntoViewIfNeededOptions.kt
> +    private val builder: IBuilder<ScrollIntoViewIfNeededOptions>
```suggestion
    @Transient private val builder: IBuilder<ScrollIntoViewIfNeededOptions>
```

2021-04-26 15:27 UTC, Roman-Mitusov approved these changes

2021-04-26 15:27 UTC, merged